### ISSUE TITLE
Seems to be not compitible with keycloak version 26?

### ISSUE THREAD

**Issue by tahir-ozdilek** [5-stones/keycloak-group-tokenmapper#1]
Hi,
First of all I thank you for your effort as i really need to map group-ids to token and in default keycloak doesnt have such functionality as far as i recognized.

I tried your custom package. After installation it came to the client-scope mapper. When i create a map from your custom mapper, I get error upon login:

{
    "error": "unknown_error",
    "error_description": "Cannot parse the JSON"
}
Also, keycloak cmd console gives run time exception too.

**Comment by jspizziri** [comment]
What version of Keycloak are you running?

**Comment by tahir-ozdilek** [comment]
version 26

**Comment by tahir-ozdilek** [comment]
> What version of Keycloak are you running?

version 26

**Comment by jspizziri** [comment]
> version 26

Sorry, I guess I didn't read the title of the issue first 😬 

We haven't tested with that version yet, so it's likely the result of a breaking change somewhere between v22 (which is what we use) and v26.

If you want to do some investigation and submit a PR I'd be happy to review.

**Comment by tahir-ozdilek** [comment]
> submit a PR

well, as i am new to keycloak, i dont have sufficient knowledge for creating my custom mapper :)
I just changed my backend design and for now, i am fine with using 'group names' in the token.
